Repository music-assistant/frontend, pull requests merged in 2023-07, with the labels that each got.

#155 Backend changes for library refactor
  src/components/InfoHeader.vue
  src/components/ItemsListing.vue
  src/components/ListviewItem.vue
  src/components/MediaItemCard.vue
  src/components/MediaItemContextMenu.vue
  src/components/MediaItemThumb.vue
  src/components/ProviderIcon.vue
  src/components/ProviderIcons.vue
  src/components/QualityDetailsBtn.vue
  src/layouts/default/PlayerOSD/PlayerFullscreen.vue
  src/layouts/default/PlayerOSD/PlayerTrackDetails.vue
  src/plugins/api/index.ts
  src/plugins/api/interfaces.ts
  src/translations/da.json
  src/translations/de.json
  src/translations/en.json
  src/translations/es.json
  src/translations/fr.json
  src/translations/it.json
  src/translations/nb.json
  src/translations/nl.json
  src/translations/pl.json
  src/utils.ts
  src/views/AlbumDetails.vue
  src/views/ArtistDetails.vue
  src/views/BrowseView.vue
  src/views/HomeView.vue
  src/views/LibraryAlbums.vue
  src/views/LibraryArtists.vue
  src/views/LibraryPlaylists.vue
  src/views/LibraryRadios.vue
  src/views/LibraryTracks.vue
  src/views/PlayerQueue.vue
  src/views/PlaylistDetails.vue
  src/views/RadioDetails.vue
  src/views/Search.vue
  src/views/TrackDetails.vue
Labels: maintenance

#156 Switch to SVG provider icons
  src/components/MediaItemContextMenu.vue
  src/components/ProviderIcon.vue
  src/components/QualityDetailsBtn.vue
  src/plugins/api/index.ts
  src/plugins/api/interfaces.ts
  src/views/settings/CoreConfigs.vue
  src/views/settings/EditCoreConfig.vue
  src/views/settings/Players.vue
  src/views/settings/Providers.vue
Labels: maintenance

#157 Fix some glitches
  src/components/ItemsListing.vue
  src/components/ListviewItem.vue
  src/components/MediaItemContextMenu.vue
  src/components/PanelviewItem.vue
  src/components/ProviderIcon.vue
  src/components/VolumeControl.vue
  src/components/mods/Container.vue
  src/components/mods/ListItem.vue
  src/layouts/default/AppBar.vue
  src/layouts/default/PlayerSelect.vue
  src/styles/global.css
  src/translations/en.json
  src/views/AlbumDetails.vue
  src/views/ArtistDetails.vue
  src/views/PlaylistDetails.vue
  src/views/RadioDetails.vue
  src/views/TrackDetails.vue
  src/views/settings/CoreConfigs.vue
  src/views/settings/Players.vue
  src/views/settings/Providers.vue
Labels: maintenance, bugfix

#158 Add some base diagnostic server info
  src/translations/en.json
  src/views/settings/CoreConfigs.vue
  src/views/settings/Settings.vue
Labels: new-feature

#161 Improve Itemdetails
  src/components/InfoHeader.vue
  src/components/ItemsListing.vue
  src/components/PanelviewItem.vue
  src/components/ProviderIcon.vue
  src/components/mods/ListItem.vue
  src/layouts/default/PlayerOSD/PlayerExtendedControls.vue
  src/layouts/default/PlayerOSD/PlayerVolume.vue
  src/plugins/api/index.ts
  src/styles/global.css
  src/translations/en.json
  src/utils.ts
  src/views/AlbumDetails.vue
  src/views/ArtistDetails.vue
  src/views/BrowseView.vue
  src/views/LibraryAlbums.vue
  src/views/LibraryArtists.vue
  src/views/LibraryPlaylists.vue
  src/views/LibraryRadios.vue
  src/views/LibraryTracks.vue
  src/views/PlaylistDetails.vue
  src/views/RadioDetails.vue
  src/views/TrackDetails.vue
  src/views/settings/CoreConfigs.vue
  src/views/settings/Players.vue
  src/views/settings/Providers.vue
Labels: maintenance

#162 Fix add to playlist
  package.json
  src/App.vue
  src/components/InfoHeader.vue
  src/components/ItemsListing.vue
  src/components/ListviewItem.vue
  src/components/MediaItemCard.vue
  src/components/MediaItemContextMenu.vue
  src/components/PanelviewItem.vue
  src/components/VolumeControl.vue
  src/components/mods/ListItem.vue
  src/helpers/contextmenu.ts
  src/helpers/index.ts
  src/helpers/utils.ts
  src/layouts/default/AddToPlaylistDialog.vue
  src/layouts/default/PlayItemDialog.vue
  src/layouts/default/PlayerOSD/Player.vue
  src/layouts/default/PlayerOSD/PlayerControlBtn/RepeatBtn.vue
  src/layouts/default/PlayerOSD/PlayerControlBtn/ShuffleBtn.vue
  src/layouts/default/PlayerOSD/PlayerTimeline.vue
  src/layouts/default/PlayerOSD/PlayerTrackDetails.vue
  src/layouts/default/PlayerSelect.vue
  src/layouts/default/View.vue
  src/plugins/eventbus.ts
  src/plugins/store.ts
  src/views/AlbumDetails.vue
  src/views/ArtistDetails.vue
  src/views/BrowseView.vue
  src/views/PlayerQueue.vue
  src/views/RadioDetails.vue
  src/views/Search.vue
  src/views/TrackDetails.vue
  yarn.lock
Labels: maintenance, bugfix

#163 Bottom mobile player
  src/components/VolumeControl.vue
  src/components/mods/Button.vue
  src/helpers/utils.ts
  src/layouts/default/NavigationMenu.vue
  src/layouts/default/PlayerOSD/Player.vue
  src/layouts/default/PlayerOSD/PlayerControlBtn/QueueBtn.vue
  src/layouts/default/PlayerOSD/PlayerControlBtn/SpeakerBtn.vue
  src/layouts/default/PlayerOSD/PlayerControlBtn/VolumeBtn.vue
  src/layouts/default/PlayerOSD/PlayerExtendedControls.vue
  src/layouts/default/PlayerOSD/PlayerFullscreen.vue
  src/layouts/default/PlayerOSD/PlayerTimeline.vue
  src/layouts/default/PlayerOSD/PlayerTrackDetails.vue
  src/layouts/default/View.vue
  src/styles/global.css
  src/views/settings/Providers.vue
Labels: maintenance

#164 Remove header and adjust all views
  src/components/InfoHeader.vue
  src/components/ItemsListing.vue
  src/components/ProviderDetails.vue
  src/components/mods/ListItem.vue
  src/layouts/default/AddToPlaylistDialog.vue
  src/layouts/default/AppBar.vue
  src/layouts/default/PlayItemDialog.vue
  src/plugins/router.ts
  src/plugins/store.ts
  src/translations/en.json
  src/views/AlbumDetails.vue
  src/views/ArtistDetails.vue
  src/views/BrowseView.vue
  src/views/LibraryAlbums.vue
  src/views/LibraryArtists.vue
  src/views/LibraryPlaylists.vue
  src/views/LibraryRadios.vue
  src/views/LibraryTracks.vue
  src/views/PlayerQueue.vue
  src/views/PlaylistDetails.vue
  src/views/RadioDetails.vue
  src/views/Search.vue
  src/views/TrackDetails.vue
  src/views/settings/CoreConfigs.vue
  src/views/settings/Players.vue
  src/views/settings/Providers.vue
  src/views/settings/Settings.vue
Labels: maintenance

#168 Button improvements
  src/components/ItemsListing.vue
  src/components/ListviewItem.vue
  src/components/mods/Button.vue
  src/components/mods/ListItem.vue
  src/helpers/utils.ts
  src/layouts/default/PlayerOSD/Player.vue
  src/layouts/default/PlayerOSD/PlayerControlBtn/PlayBtn.vue
  src/layouts/default/PlayerOSD/PlayerControlBtn/QueueBtn.vue
  src/layouts/default/PlayerOSD/PlayerControlBtn/SpeakerBtn.vue
  src/layouts/default/PlayerOSD/PlayerControlBtn/VolumeBtn.vue
  src/layouts/default/PlayerOSD/PlayerControls.vue
  src/layouts/default/PlayerOSD/PlayerExtendedControls.vue
  src/layouts/default/PlayerOSD/PlayerFullscreen.vue
  src/layouts/default/PlayerOSD/PlayerTimeline.vue
  src/plugins/api/interfaces.ts
  src/views/settings/CoreConfigs.vue
  src/views/settings/Providers.vue
Labels: maintenance

#170 Some small adjustments to the settings pages
  src/helpers/contextmenu.ts
  src/plugins/i18n.ts
  src/translations/en.json
  src/views/LibraryAlbums.vue
  src/views/PlaylistDetails.vue
  src/views/settings/CoreConfigs.vue
  src/views/settings/Players.vue
  src/views/settings/Providers.vue
  src/views/settings/Settings.vue
Labels: maintenance

#169 mobile player color schema correction
  src/components/ItemsListing.vue
  src/components/PanelviewItem.vue
  src/components/mods/Button.vue
  src/components/mods/Container.vue
  src/components/mods/ListItem.vue
  src/components/mods/ListViewItemContainer.vue
  src/layouts/default/PlayerOSD/Player.vue
  src/layouts/default/PlayerOSD/PlayerControlBtn/PlayBtn.vue
  src/layouts/default/PlayerOSD/PlayerControlBtn/QueueBtn.vue
  src/layouts/default/PlayerOSD/PlayerControlBtn/SpeakerBtn.vue
  src/layouts/default/PlayerOSD/PlayerControlBtn/VolumeBtn.vue
  src/layouts/default/PlayerOSD/PlayerExtendedControls.vue
  src/layouts/default/PlayerOSD/PlayerTrackDetails.vue
  src/styles/global.css
  src/views/settings/Providers.vue
Labels: maintenance

#175 Rework Navigation
  public/favicon.svg
  public/index.html
  src/App.vue
  src/assets/JetBrainsMono-Medium.woff2
  src/assets/hass.png
  src/assets/icon.svg
  src/assets/logo.png
  src/assets/logo.svg
  src/components/InfoHeader.vue
  src/components/ItemsListing.vue
  src/components/MediaItemThumb.vue
  src/components/ProviderDetails.vue
  src/components/QualityDetailsBtn.vue
  src/components/VolumeControl.vue
  src/helpers/utils.ts
  src/layouts/default/BottomNavigation.vue
  src/layouts/default/ButtomNavigation.vue
  src/layouts/default/Default.vue
  src/layouts/default/DrawerNavigation.vue
  src/layouts/default/Footer.vue
  src/layouts/default/PlayerOSD/Player.vue
  src/layouts/default/PlayerOSD/PlayerControlBtn/SpeakerBtn.vue
  src/layouts/default/PlayerOSD/PlayerExtendedControls.vue
  src/layouts/default/PlayerOSD/PlayerTrackDetails.vue
  src/plugins/router.ts
  src/plugins/store.ts
  src/styles/_variables.scss
  src/styles/global.css
  src/styles/settings.scss
  src/translations/en.json
  src/views/AlbumDetails.vue
  src/views/BrowseView.vue
  src/views/LibraryAlbums.vue
  src/views/LibraryArtists.vue
  src/views/LibraryPlaylists.vue
  src/views/LibraryRadios.vue
  src/views/LibraryTracks.vue
  src/views/PlayerQueue.vue
  src/views/TrackDetails.vue
  src/views/settings/CoreConfigs.vue
  src/views/settings/EditConfig.vue
  src/views/settings/Players.vue
  src/views/settings/Providers.vue
  src/views/settings/Settings.vue
Labels: maintenance, bugfix

#186 Several small bugfixes
  env.d.ts
  package.json
  src/components/ItemsListing.vue
  src/components/PanelviewItem.vue
  src/components/mods/Container.vue
  src/plugins/api/interfaces.ts
  src/shims-vue-virtual-scroller.d.ts
  src/translations/da.json
  src/translations/de.json
  src/translations/en.json
  src/translations/es.json
  src/translations/fr.json
  src/translations/it.json
  src/translations/nb.json
  src/translations/nl.json
  src/translations/pl.json
  src/views/AlbumDetails.vue
  src/views/ArtistDetails.vue
  src/views/BrowseView.vue
  src/views/LibraryAlbums.vue
  src/views/LibraryArtists.vue
  src/views/LibraryPlaylists.vue
  src/views/LibraryRadios.vue
  src/views/LibraryTracks.vue
  src/views/PlayerQueue.vue
  src/views/PlaylistDetails.vue
  src/views/Search.vue
  src/views/TrackDetails.vue
  src/views/settings/Providers.vue
  yarn.lock
Labels: bugfix
