Repository music-assistant/frontend, pull requests merged in 2023-10, with the labels that each got.

#219 Use specific dependency version
  package.json
  yarn.lock
Labels: dependencies

#206 Update release.yml
  .github/workflows/release.yml
Labels: ci

#239 Lokalise: Translations update
  src/translations/uk_UA.json
Labels: translations, maintenance

#252 A few small fixes
  src/components/ItemsListing.vue
  src/layouts/default/PlayerSelect.vue
  src/plugins/router.ts
  src/views/settings/Providers.vue
Labels: bugfix
