Repository music-assistant/frontend, pull requests merged in 2024-06, with the labels that each got.

#512 Try again. Seems to keep reverting
  src/translations/en.json
Labels: translations, maintenance

#518 Centre the media controls (and simplify some CSS along the way)
  src/layouts/default/PlayerOSD/Player.vue
Labels: maintenance

#528 Fix Audio Output Device client settings for companion app
  src/views/settings/ClientConfigs.vue
Labels: bugfix

#530 Optimize all paged listings
  src/components/HomeWidgetRows.vue
  src/components/ItemsListing.vue
  src/components/ProviderDetails.vue
  src/layouts/default/AddToPlaylistDialog.vue
  src/layouts/default/PlayerOSD/PlayerFullscreen.vue
  src/plugins/api/index.ts
  src/plugins/api/interfaces.ts
  src/plugins/store.ts
  src/views/BrowseView.vue
  src/views/LibraryAlbums.vue
  src/views/LibraryArtists.vue
  src/views/LibraryPlaylists.vue
  src/views/LibraryRadios.vue
  src/views/LibraryTracks.vue
  src/views/settings/CoreConfigs.vue
Labels: maintenance, bugfix

#532 Update languages
  src/translations/en.json
Labels: translations, maintenance

#544 Revert "Lokalise: Translations update"
  cs/cs.json
  da/da.json
  de/de.json
  el_GR/el_GR.json
  en/en.json
  en_AU/en_AU.json
  en_GB/en_GB.json
  es/es.json
  fr/fr.json
  he/he.json
  is_IS/is_IS.json
  it/it.json
  nb/nb.json
  nl/nl.json
  pl/pl.json
  pt_BR/pt_BR.json
  ru_RU/ru_RU.json
  sr/sr.json
  sr_Latn/sr_Latn.json
  sv_SE/sv_SE.json
  uk_UA/uk_UA.json
  zh_CN/zh_CN.json
Labels: bugfix

#548 Various minor improvements
  src/translations/en.json
Labels: maintenance

#559 Lokalise-cron-download
  .github/workflows/lokalise-download.yml
Labels: new-feature, github_actions
