Repository music-assistant/frontend, pull requests merged in 2024-07, with the labels that each got.

#563 Remove languages not mostly translated
  src/translations/en.json
Labels: maintenance

#578 Update lokalise-download.yml
  .github/workflows/lokalise-download.yml
Labels: bugfix, github_actions

#585 Open fullscreen player from URL
  src/App.vue
  src/layouts/default/Default.vue
  src/layouts/default/ItemContextMenu.vue
  src/plugins/api/index.ts
  src/plugins/router.ts
  src/plugins/store.ts
  src/views/HomeView.vue
  src/views/LibraryRadios.vue
  src/views/LibraryTracks.vue
Labels: new-feature
