Repository music-assistant/frontend, pull requests merged in 2024-02, with the labels that each got.

#349 Add album to playlist
  src/helpers/contextmenu.ts
  src/layouts/default/AddToPlaylistDialog.vue
Labels: new-feature

#350 Add a badge for when search is filtering results
  src/components/ItemsListing.vue
  src/translations/en.json
Labels: new-feature

#347 Add wheel event to PlayerVolume component
  src/layouts/default/PlayerOSD/PlayerVolume.vue
Labels: maintenance

#371 Handle provider set-up depending on another provider
  src/plugins/api/index.ts
  src/plugins/api/interfaces.ts
  src/translations/en.json
  src/views/settings/Providers.vue
Labels: new-feature

#373 Remove duplicate [default]
  src/translations/en.json
Labels: translations, maintenance

#374 Changes to when and how the player row cards are shown
  src/components/PanelviewPlayerCard.vue
  src/views/HomeView.vue
Labels: maintenance

#378 Fix homescreen widgets for radio and playlists
  src/views/HomeView.vue
Labels: bugfix

#376 Fix the weird behaviour with the search field and badge
  src/components/ItemsListing.vue
Labels: maintenance, bugfix

#300 Add heart icon to grid view
  src/components/FavoriteButton.vue
  src/components/ItemsListing.vue
  src/components/ListviewItem.vue
  src/components/PanelviewItem.vue
Labels: new-feature

#389 Remove unused ellipsis
  src/layouts/default/PlayerOSD/PlayerFullscreen.vue
Labels: maintenance

#388 Reworked Home View Page
  package.json
  src/components/Carousel.vue
  src/components/ItemsListing.vue
  src/helpers/utils.ts
  src/layouts/default/PlayerOSD/PlayerFullscreen.vue
  src/plugins/index.ts
  src/plugins/router.ts
  src/plugins/swiper.ts
  src/styles/settings.scss
  src/views/HomeView.vue
  tsconfig.json
  yarn.lock
Labels: maintenance

#390 Improved paths
  src/App.vue
  src/components/InfoHeader.vue
  src/components/ItemsListing.vue
  src/components/ListviewItem.vue
  src/components/MediaItemThumb.vue
  src/components/PanelviewItem.vue
  src/components/ProviderDetails.vue
  src/components/ProviderIcon.vue
  src/components/VolumeControl.vue
  src/views/AlbumDetails.vue
  src/views/ArtistDetails.vue
  src/views/BrowseView.vue
  src/views/HomeView.vue
  src/views/LibraryAlbums.vue
  src/views/LibraryArtists.vue
  src/views/LibraryPlaylists.vue
  src/views/LibraryRadios.vue
  src/views/LibraryTracks.vue
  src/views/PlayerQueue.vue
  src/views/PlaylistDetails.vue
  src/views/RadioDetails.vue
  src/views/Search.vue
  src/views/TrackDetails.vue
  tsconfig.json
Labels: maintenance

#391 Various small tweaks and fixes
  src/components/MediaItemCard.vue
  src/components/PanelviewPlayerCard.vue
  src/components/QualityDetailsBtn.vue
  src/layouts/default/PlayItemDialog.vue
  src/layouts/default/PlayerOSD/Player.vue
  src/layouts/default/PlayerOSD/PlayerControlBtn/NextBtn.vue
  src/layouts/default/PlayerOSD/PlayerControlBtn/PlayBtn.vue
  src/layouts/default/PlayerOSD/PlayerControlBtn/PreviousBtn.vue
  src/layouts/default/PlayerOSD/PlayerControlBtn/RepeatBtn.vue
  src/layouts/default/PlayerOSD/PlayerControlBtn/ShuffleBtn.vue
  src/layouts/default/PlayerOSD/PlayerControlBtn/SpeakerBtn.vue
  src/layouts/default/PlayerOSD/PlayerControlBtn/VolumeBtn.vue
  src/layouts/default/PlayerOSD/PlayerControls.vue
  src/layouts/default/PlayerOSD/PlayerFullscreen.vue
  src/layouts/default/PlayerOSD/PlayerTimeline.vue
  src/layouts/default/PlayerOSD/PlayerTrackDetails.vue
  src/layouts/default/PlayerSelect.vue
  src/plugins/store.ts
  src/views/HomeView.vue
  src/views/PlayerQueue.vue
Labels: maintenance, bugfix

#400 Fix for now playing widget
  src/components/PanelviewPlayerCard.vue
  src/views/HomeView.vue
Labels: bugfix

#401 Fix icons on panel view
  src/components/PanelviewItem.vue
Labels: maintenance, bugfix
