Repository music-assistant/frontend, pull requests merged in 2024-05, with the labels that each got.

#462 Feature: search for radio stream title from full screen player
  src/layouts/default/PlayerOSD/PlayerFullscreen.vue
Labels: new-feature

#480 Global styling duplication fix
  src/App.vue
  src/components/ItemsListing.vue
  src/styles/global.css
  src/styles/settings.scss
Labels: maintenance, bugfix

#487 Fix PlayerTimeline stopDragging
  src/layouts/default/PlayerOSD/PlayerTimeline.vue
Labels: bugfix

#488 Fix: Search ignores last press sometimes
  src/views/Search.vue
Labels: bugfix, javascript

#490 Match menu to tooltip
  src/translations/en.json
Labels: maintenance

#491 Improve the out of the box experience a bit
  src/components/HomeCurrentlyPlayingRow.vue
  src/components/PanelviewPlayerCard.vue
  src/layouts/default/DrawerNavigation.vue
  src/layouts/default/PlayerOSD/PlayerControlBtn/PlayBtn.vue
  src/layouts/default/PlayerOSD/PlayerControlBtn/SpeakerBtn.vue
  src/layouts/default/PlayerOSD/PlayerControlBtn/VolumeBtn.vue
  src/layouts/default/PlayerOSD/PlayerExtendedControls.vue
  src/layouts/default/PlayerOSD/PlayerFullscreen.vue
  src/layouts/default/PlayerOSD/PlayerTrackDetails.vue
  src/layouts/default/PlayerSelect.vue
  src/plugins/api/index.ts
  src/plugins/router.ts
  src/plugins/store.ts
  src/translations/en.json
  src/views/HomeView.vue
  src/views/settings/Providers.vue
Labels: maintenance, bugfix

#492 Fix issues with items listings
  src/components/ItemsListing.vue
  src/components/MediaItemThumb.vue
  src/views/BrowseView.vue
  src/views/PlaylistDetails.vue
Labels: bugfix

#493 Fix back button in toolbar
  src/components/Toolbar.vue
Labels: bugfix

#504 Match menu to tooltip
  src/translations/en.json
Labels: maintenance
