Repository music-assistant/frontend, pull requests merged in 2025-04, with the labels that each got.

#948 fix: Built-in Web Player Part 4
  src/components/BuiltinPlayer.vue
  src/plugins/web_player.ts
Labels: bugfix

#962 add open home badge
  README.md
Labels: maintenance

#960 feat: Add lyrics viewer component
  src/components/LyricsViewer.vue
  src/layouts/default/PlayerOSD/PlayerFullscreen.vue
  src/plugins/api/interfaces.ts
  src/translations/en.json
Labels: new-feature
