Repository music-assistant/frontend, pull requests merged in 2025-02, with the labels that each got.

#842 feat: group players with identical DSPs together in the Audio Pipeline
  src/components/QualityDetailsBtn.vue
Labels: maintenance

#851 fix: remove `is_leader` from `DSPDetails` model
  src/plugins/api/interfaces.ts
Labels: bugfix

#852 feat: make players list expandable in the Audio Pipeline
  src/components/QualityDetailsBtn.vue
  src/translations/en.json
Labels: new-feature

#853 fix: increase Audio pipeline width
  src/components/QualityDetailsBtn.vue
Labels: bugfix

#865 Implement consistent behavior for clicking an item or play button
  src/components/HomeWidgetRow.vue
  src/components/InfoHeader.vue
  src/components/ItemsListing.vue
  src/components/ListviewItem.vue
  src/components/MenuButton.vue
  src/components/PanelviewItem.vue
  src/components/PanelviewItemCompact.vue
  src/components/PlayerCard.vue
  src/helpers/utils.ts
  src/layouts/default/ItemContextMenu.vue
  src/layouts/default/PlayerSelect.vue
  src/plugins/api/index.ts
  src/plugins/eventbus.ts
  src/plugins/store.ts
  src/translations/en.json
Labels: maintenance

#887 Fix: Select all in search view
  src/components/ItemsListing.vue
  src/translations/en.json
  src/views/Search.vue
Labels: bugfix

#885 Feat: improved Notification support
  src/App.vue
  src/assets/5_mins_of_silence.mp3
  src/assets/almost_silent.mp3
  src/helpers/useMediaBrowserMetaData.ts
  src/layouts/default/PlayerOSD/PlayerBrowserMediaControls.vue
  src/plugins/web_player.ts
Labels: bugfix, new-feature

#888 Fix: Improved colors in fullscreen player
  src/helpers/utils.ts
  src/layouts/default/PlayerOSD/Player.vue
  src/layouts/default/PlayerOSD/PlayerFullscreen.vue
  src/layouts/default/PlayerOSD/PlayerTimeline.vue
Labels: bugfix
