Repository music-assistant/frontend, pull requests merged in 2025-01, with the labels that each got.

#801 Fix: Improve spacing/padding consistency accross DSP Settings
  src/components/dsp/DSPParametricEQ.vue
  src/components/dsp/DSPSlider.vue
  src/components/dsp/DSPToneControl.vue
  src/views/settings/EditPlayerDsp.vue
Labels: maintenance

#808 fix: Use a better solution to watch params
  src/layouts/default/Default.vue
  src/plugins/router.ts
  src/views/HomeView.vue
Labels: bugfix

#820 chore: Fix frameless for side menu
  src/layouts/default/Default.vue
  src/layouts/default/View.vue
  src/plugins/store.ts
Labels: bugfix

#821 chore: Hide double scroll
  src/styles/global.css
Labels: bugfix

#819 fix: Prevent racing condition to cause issue
  src/layouts/default/Default.vue
Labels: bugfix

#823 Fix: Remove links to DSP Settings for PlayerGroups
  src/helpers/player_menu_items.ts
  src/views/settings/EditPlayer.vue
  src/views/settings/Players.vue
Labels: bugfix

#824 Fix: Allow opening of DSP Settings on unavailable players
  src/views/settings/Players.vue
Labels: bugfix

#840 feat: add preamp support for the Parametric Equalizer
  src/components/dsp/DSPParametricEQ.vue
  src/plugins/api/interfaces.ts
  src/translations/en.json
  src/views/settings/EditPlayerDsp.vue
Labels: new-feature

#841 Handle player controls for power and volume
  src/components/PlayerCard.vue
  src/components/VolumeControl.vue
  src/helpers/player_menu_items.ts
  src/layouts/default/PlayerOSD/Player.vue
  src/layouts/default/PlayerOSD/PlayerFullscreen.vue
  src/layouts/default/PlayerOSD/PlayerTimeline.vue
  src/layouts/default/PlayerOSD/PlayerTrackDetails.vue
  src/layouts/default/PlayerOSD/PlayerVolume.vue
  src/layouts/default/PlayerSelect.vue
  src/plugins/api/index.ts
  src/plugins/api/interfaces.ts
  src/plugins/store.ts
  src/translations/en.json
  src/views/settings/AddPlayerGroup.vue
  src/views/settings/Players.vue
Labels: maintenance, new-feature
