Repository music-assistant/frontend, pull requests merged in 2025-03, with the labels that each got.

#898 Fix: More search fixes
  src/components/ItemsListing.vue
  src/translations/en.json
  src/views/AlbumDetails.vue
Labels: maintenance, bugfix

#886 Feat: Move the output limiter option from DSP to Player Settings
  src/plugins/api/interfaces.ts
  src/translations/en.json
  src/views/settings/EditPlayerDsp.vue
Labels: maintenance

#902 Feat: Built-in Web Player Provider
  src/App.vue
  src/components/BuiltinPlayer.vue
  src/components/PlayerCard.vue
  src/layouts/default/PlayerSelect.vue
  src/plugins/api/index.ts
  src/plugins/api/interfaces.ts
  src/plugins/web_player.ts
Labels: new-feature

#901 Allow RTSP URLs for Builtin Provider
  src/components/AddManualLink.vue
Labels: enhancement

#912 Fix: Invalid URL with the built-in Web Player
  src/plugins/web_player.ts
Labels: bugfix

#914 Feat: Make the frequency slider behave logarithmically
  src/components/dsp/DSPSlider.vue
  src/components/dsp/DSPToneControl.vue
Labels: enhancement

#917 Feat: Mutichannel Parametric Equalizer
  src/components/dsp/DSPParametricEQ.vue
  src/plugins/api/interfaces.ts
  src/translations/en.json
  src/views/settings/EditPlayerDsp.vue
Labels: new-feature

#918 feat: Built-in Web Player Part 2
  src/App.vue
  src/components/BuiltinPlayer.vue
  src/components/PlayerCard.vue
  src/helpers/utils.ts
  src/layouts/default/PlayerSelect.vue
  src/plugins/api/interfaces.ts
  src/plugins/web_player.ts
Labels: enhancement

#937 Implement (configurable) recommendation rows on homescreen
  src/App.vue
  src/components/HomeWidgetRow.vue
  src/components/HomeWidgetRows.vue
  src/components/ItemsListing.vue
  src/components/PanelviewItemCompact.vue
  src/components/PlayerCard.vue
  src/components/WidgetRow.vue
  src/helpers/utils.ts
  src/plugins/api/index.ts
  src/plugins/api/interfaces.ts
  src/translations/en.json
  src/views/HomeView.vue
  src/views/Search.vue
Labels: new-feature

#938 fix: Built-in Web Player Part 3
  src/App.vue
  src/components/BuiltinPlayer.vue
  src/layouts/default/PlayerSelect.vue
  src/plugins/api/index.ts
  src/plugins/web_player.ts
Labels: bugfix, enhancement

#939 Lokalise: Translations update
  src/translations/en.json
  src/translations/fr.json
  src/translations/nl.json
Labels: maintenance
